### ISSUE TITLE
FileNotFound exception

### ISSUE THREAD

**Issue by nachtien** [peterLaurence/MapCompose#2]
Attached is the image I am using.

With libvps I ran the following to generate the deep zoom images:
`vips dzsave floorplan.png output --layout=google --tile-size=256 --suffix .jpg --vips-progress`

```
2021-11-17 18:43:18.070 11300-11329/com.achtien.mapcompose4 E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-3
    Process: com.achtien.mapcompose4, PID: 11300
    java.io.FileNotFoundException: output/4/6/0.jpg
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:881)
        at android.content.res.AssetManager.open(AssetManager.java:858)
        at com.achtien.mapcompose4.MainActivity$onCreate$tileStreamProvider$1.getTileStream(MainActivity.kt:26)
        at ovh.plrapps.mapcompose.core.TileCollector$worker$1.invokeSuspend(TileCollector.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Android code:
```kotlin
class MainActivity : ComponentActivity() {
	override fun onCreate(savedInstanceState: Bundle?) {
		super.onCreate(savedInstanceState)
		val tileStreamProvider =
			TileStreamProvider { row, col, zoomLvl ->
				resources.assets.open("output/$zoomLvl/$row/$col.jpg")
			}
		val state: MapState by mutableStateOf(
			MapState(5, 4683, 2889, tileStreamProvider).apply {
				disableRotation()
			}
		)
		setContent {
			MapCompose4Theme {
				MapUI(state = state)
			}
		}
	}
}
```
![floorplan](https://user-images.githubusercontent.com/116726/142321145-a6338c6a-bab9-407f-b30f-55e3911a1044.png)

**Comment by peterLaurence** [comment]
You didn't put your tiles in the right folder (in the assets). The "assets" folder must be in `src/main/`.
The demo app is a good example. Clone the repo, run it.

**Comment by peterLaurence** [comment]
If you can't find the issue, share your github project. I'll have a look.

**Comment by nachtien** [comment]
[MapCompose4.zip](https://github.com/peterLaurence/MapCompose/files/7562936/MapCompose4.zip)
Thanks. The map is trying to load files that don't exist from what's generated. It's loading other files though.

**Comment by peterLaurence** [comment]
Here you go:

```
class MainActivity : ComponentActivity() {
	override fun onCreate(savedInstanceState: Bundle?) {
		super.onCreate(savedInstanceState)
		val tileStreamProvider =
			TileStreamProvider { row, col, zoomLvl ->
				kotlin.runCatching {
					resources.assets.open("output/$zoomLvl/$row/$col.jpg")
				}.getOrNull()

			}
		val state: MapState by mutableStateOf(
			MapState(6, 4683, 2889, tileStreamProvider).apply {
				disableRotation()
			}
		)
		setContent {
			MapCompose4Theme {
				MapUI(state = state)
			}
		}
	}
}
```

There were two mistakes:
- MapCompose requests tiles, but if some tiles are missing, your `TileStreamProvider` shouldn't throw an exception. It can just ruturn null.
- Your map has 6 levels, not 5 (levels are 0-indexed).

Fair warning: you're using compose 1.1 beta. MapCompose is only tested on the stable branch at the moment (1.0.5 is the last version).

**Comment by nachtien** [comment]
holy crap this is a cool library, thanks!!
